### ISSUE TITLE
In mass-generation, Audio field is replaced even if not asked to

### ISSUE THREAD

**Issue by dmgerman** [mass-immersion-approach/MIA-Japanese-Add-on#46]
**Type:**
  - [ x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Macos

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [ x] no

**Description:**
[ Write the issue description here ]

In the bulk-add-readings, everything works, except that, if there is a field called Audio, it is replaced, even if not asked to. 

My scenario: I have 1000 cards, with 15 fields, including Audio. I asked the bulk-add-readings to replace the field meaningFuri (overwrite). For every card, this field is replaced, but also the field Audio.

The work around was to rename the field Audio to AudioNot and then back.

**Comment by LucasMIA** [comment]
Hey, this is not a bug. Please check out the guide on the MIA website. If you choose to export audio files and/or pitch accent graphs along with the furigana and accent information then it will be exported to the fields designated in the settings menu and according to the rules in that menu (ie add, overwrite, or if empty). Audio is the default name for the field which is why your audio field was probably getting overwritten. We agree that this is confusing functionality (it has not been changed although other parts of mass export have changed, which leads to even more confusion) though and may change it so that audio files and pitch accent graphs each have their own destination fields at some point in the future, for the time being I suggest you read the section of the guide about mass exporting if you would like to better understand how it functions. Anyways, can you confirm with me that this is what's happening and if you can't confirm it then please post a picture of your settings.

**Comment by dmgerman** [comment]
Thank you. You are correct. One suggestion: perhaps add a message saying that the other field will be overwritten (if the option is selected).

thank you again for your response.
